# Generated by Django 4.1.3 on 2022-12-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_potential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
