# Generated by Django 4.1.3 on 2022-12-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_our_potential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_potential',
            name='heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='our_potential',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
