# Generated by Django 4.1.3 on 2022-12-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_our_potential_heading_alter_our_potential_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_u',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=40000)),
            ],
        ),
    ]
