# Generated by Django 4.1.3 on 2023-01-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_about_u'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=40000)),
                ('image', models.ImageField(blank=True, default='uploads/image-icon.jpg', upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
