# Generated by Django 4.1.3 on 2023-01-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='heading',
        ),
    ]
