# Generated by Django 4.1.3 on 2023-01-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_comment_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_of_the_user',
        ),
    ]
