# Generated by Django 4.1.3 on 2023-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_rename_text_comment_comment_of_the_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_of_the_user',
            field=models.TextField(max_length=40000),
        ),
    ]
