# Generated by Django 4.1.3 on 2023-01-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_comment_comment_of_the_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='name_of_the_user',
        ),
    ]
