# Generated by Django 4.1.3 on 2023-01-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_rename_name_comment_name_of_the_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_description', models.TextField(max_length=40000)),
                ('image', models.ImageField(blank=True, default='uploads/image-icon.jpg', upload_to='uploads/%Y/%m/%d/')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
