# Generated by Django 4.1.3 on 2023-01-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_rename_product_name_product_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_other_image',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallery_top_image',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
