# Generated by Django 4.1.3 on 2023-01-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_gallery_other_image_date_gallery_top_image_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery_top_image',
            options={'ordering': ['-date']},
        ),
    ]
