# Generated by Django 4.1.3 on 2023-01-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_rename_image_gallery_other_image_imag3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('comment_of_the_user', models.TextField(max_length=40000)),
            ],
        ),
    ]
