# Generated by Django 4.1.3 on 2023-01-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_gallery_bottom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_bottom',
            old_name='comment_of_the_user',
            new_name='description',
        ),
    ]
