# Generated by Django 4.1.3 on 2023-01-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_rename_comment_of_the_user_gallery_bottom_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_other_image',
            old_name='imag3',
            new_name='image3',
        ),
    ]
