# Generated by Django 4.1.3 on 2023-01-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
