# Generated by Django 4.1.3 on 2023-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='none', unique=True),
            preserve_default=False,
        ),
    ]
