# Generated by Django 4.1.3 on 2023-01-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_u',
            options={'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='gallery_bottom',
            options={'verbose_name_plural': 'gallery buttom'},
        ),
        migrations.AlterModelOptions(
            name='gallery_other_image',
            options={'verbose_name_plural': 'Other images in gallery'},
        ),
        migrations.AlterModelOptions(
            name='gallery_top_image',
            options={'verbose_name_plural': 'Top images in gallery'},
        ),
        migrations.AlterModelOptions(
            name='our_potential',
            options={'verbose_name_plural': 'Our potentials'},
        ),
    ]
